### ISSUE TITLE
using local db for DSN value

### ISSUE THREAD

**Issue by chrisbward** [ytsruh/gorm-libsql#8]
Hi, when I do the folllowing;
```
conn, err := gorm.Open(sqlite.New(sqlite.Config{
		DSN:        "file:local.db?parseTime=true",
		DriverName: "libsql",
	}), &gorm.Config{})
```

A file appears called "file:local.db?parseTime=true" and I don't think this is the intention with sqlite? 
New to this driver

**Comment by ytsruh** [comment]
Hmmm interesting. I spent an hour this morning trying to replicate this and couldn't. My file was always created as "local.db". Any chance you could get a minimal repo for me or gist?

Have you tried this with the standard sqlite driver from Gorm? I doubt this driver is specifically causing the issue given how lightweight it is but I will certainly look into it.

**Comment by ytsruh** [comment]
Hi, im closing this as I'm archving the repo since the original change has been merged in. Reach out to me on twitter if you have any issues
